version: '3.8'

networks:
  shared_network:
    driver: bridge

services:
    redis:
        image: redislabs/redisearch:latest
        ports:
            - "6379:6379"
        networks:
            - shared_network

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        networks:
            - shared_network
        depends_on:
            - redis
            - worker
        volumes:
            - shared-data:/all-rag-tester/data

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "
            celery -A app.worker.celery_config worker --loglevel=info"
        networks:
            - shared_network
        depends_on:
            - redis
        volumes:
            - shared-data:/all-rag-tester/data

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        command: streamlit run frontend/streamlit_app.py
        ports:
            - "8501:8501"
        networks:
            - shared_network
        depends_on:
            - backend

volumes:
  shared-data: